package cn.itbaizhan.model;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class TAdmin implements java.io.Serializable {

	// Fields

	private Integer userId;

	private String userName;

	private String userPw;
	
	private String userType;

	// Constructors

	/** default constructor */
	public TAdmin() {
	}

	/** full constructor */
	

	// Property accessors


	public String getUserName() {
		return this.userName;
	}

	public TAdmin(Integer userId, String userName, String userPw,
			String userType) {
		super();
		this.userId = userId;
		this.userName = userName;
		this.userPw = userPw;
		this.userType = userType;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return this.userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public Integer getUserId()
	{
		return userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}
	
	

}