package cn.itbaizhan.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable
{

	// Fields

	private Integer goodsId;

	private String goodsName;

	private String goodsMiaoshu;

	private String goodsPic;

	private String goodsYanse;

	private Integer goodsShichangjia;

	

	private String goodsIsnottejia;

	private String goodsIsnottuijian;

	private Integer goodsCatelogId;
	
	private String goodsDel;
	
	private String goodsCatelogName;//���ݿ��û�У��Լ���ӵ�
	
	private String goodsCount;
	
	private Integer goodsDianji=0;
	
	private Integer goodsKucun=0;
	

	// Constructors

	/** default constructor */
	public TGoods()
	{
	}

	/** full constructor */
	public TGoods(String goodsName, String goodsMiaoshu, String goodsPic,
			String goodsYanse, Integer goodsShichangjia, 
			String goodsIsnottejia, String goodsIsnottuijian,
			Integer goodsCatelogId,Integer goodsDianji)
	{
		this.goodsName = goodsName;
		this.goodsMiaoshu = goodsMiaoshu;
		this.goodsPic = goodsPic;
		this.goodsYanse = goodsYanse;
		this.goodsShichangjia = goodsShichangjia;
		
		this.goodsIsnottejia = goodsIsnottejia;
		this.goodsIsnottuijian = goodsIsnottuijian;
		this.goodsCatelogId = goodsCatelogId;
		this.goodsDianji = goodsDianji;
	}

	// Property accessors

	public Integer getGoodsId()
	{
		return this.goodsId;
	}

	public String getGoodsDel()
	{
		return goodsDel;
	}

	public void setGoodsDel(String goodsDel)
	{
		this.goodsDel = goodsDel;
	}

	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}

	public String getGoodsName()
	{
		return this.goodsName;
	}

	public void setGoodsName(String goodsName)
	{
		this.goodsName = goodsName;
	}

	public String getGoodsMiaoshu()
	{
		return this.goodsMiaoshu;
	}

	public void setGoodsMiaoshu(String goodsMiaoshu)
	{
		this.goodsMiaoshu = goodsMiaoshu;
	}

	public String getGoodsPic()
	{
		return this.goodsPic;
	}

	public void setGoodsPic(String goodsPic)
	{
		this.goodsPic = goodsPic;
	}

	public String getGoodsYanse()
	{
		return this.goodsYanse;
	}

	public void setGoodsYanse(String goodsYanse)
	{
		this.goodsYanse = goodsYanse;
	}

	public Integer getGoodsShichangjia()
	{
		return this.goodsShichangjia;
	}

	public void setGoodsShichangjia(Integer goodsShichangjia)
	{
		this.goodsShichangjia = goodsShichangjia;
	}

	

	public String getGoodsIsnottejia()
	{
		return this.goodsIsnottejia;
	}

	public void setGoodsIsnottejia(String goodsIsnottejia)
	{
		this.goodsIsnottejia = goodsIsnottejia;
	}

	public String getGoodsIsnottuijian()
	{
		return this.goodsIsnottuijian;
	}

	public void setGoodsIsnottuijian(String goodsIsnottuijian)
	{
		this.goodsIsnottuijian = goodsIsnottuijian;
	}

	public Integer getGoodsCatelogId()
	{
		return this.goodsCatelogId;
	}

	public void setGoodsCatelogId(Integer goodsCatelogId)
	{
		this.goodsCatelogId = goodsCatelogId;
	}

	public String getGoodsCatelogName()
	{
		return goodsCatelogName;
	}

	public void setGoodsCatelogName(String goodsCatelogName)
	{
		this.goodsCatelogName = goodsCatelogName;
	}

	public String getGoodsCount() {
		return goodsCount;
	}

	public void setGoodsCount(String goodsCount) {
		this.goodsCount = goodsCount;
	}

	public Integer getGoodsDianji() {
		return goodsDianji;
	}

	public void setGoodsDianji(Integer goodsDianji) {
		this.goodsDianji = goodsDianji;
	}

	public Integer getGoodsKucun() {
		return goodsKucun;
	}

	public void setGoodsKucun(Integer goodsKucun) {
		this.goodsKucun = goodsKucun;
	}

	
	
	
	

}