package cn.itbaizhan.model;

/**
 * TOrder generated by MyEclipse Persistence Tools
 */

public class TPing implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String orderId;
	private String orderitemId;
	
	

	private String goodsId;

	private String mingcheng;
	
	private String userId;

	private String loginname;
	

	private String info;
	
	private String adddate;

	// Constructors

	/** default constructor */
	public TPing()
	{
	}

	public TPing(Integer id, String orderId, String orderitemId,
			String goodsId, String mingcheng, String userId, String loginname,
			String info, String adddate) {
		super();
		this.id = id;
		this.orderId = orderId;
		this.orderitemId = orderitemId;
		this.goodsId = goodsId;
		this.mingcheng = mingcheng;
		this.userId = userId;
		this.loginname = loginname;
		this.info = info;
		this.adddate = adddate;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getOrderitemId() {
		return orderitemId;
	}

	public void setOrderitemId(String orderitemId) {
		this.orderitemId = orderitemId;
	}

	public String getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	public String getMingcheng() {
		return mingcheng;
	}

	public void setMingcheng(String mingcheng) {
		this.mingcheng = mingcheng;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getAdddate() {
		return adddate;
	}

	public void setAdddate(String adddate) {
		this.adddate = adddate;
	}

	 

}